version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /CodeBuild/Docker_Username
    DOCKER_REGISTRY_PASSWORD: /CodeBuild/Docker_Password
    DOCKER_REGISTRY_URL: /CodeBuild/docker-registry_url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-monitor-project:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-monitor-project:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"

  
